sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 5

script:
  - make qa
  - TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make brand

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker
    - env: SERVICE=recipes-id-generator
      services:
        - docker